#!/bin/sh

PREREQ=""
prereqs()
{
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

set +e

USERNAME=ananas
if [ -f /root/etc/casper.conf ]; then
    # shellcheck disable=SC1091
    . /root/etc/casper.conf
fi

if [ -n "$USERNAME" ]; then
    echo "${USERNAME}:${USERNAME}" | chroot /root chpasswd
fi

mkdir -p /root/etc/lightdm/lightdm.conf.d
cat > /root/etc/lightdm/lightdm.conf.d/50-ananas-live.conf << EOF
[LightDM]
minimum-vt=1

[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=xfce
autologin-user=${USERNAME}
autologin-user-timeout=0
autologin-session=xfce
allow-guest=false
display-setup-script=/usr/local/bin/ananas-display-setup
session-setup-script=/usr/local/bin/ananas-plymouth-quit
EOF

mkdir -p /root/etc/systemd/system/multi-user.target.wants
if [ -e /root/usr/lib/systemd/system/ssh.service ]; then
    ln -sfn /usr/lib/systemd/system/ssh.service /root/etc/systemd/system/multi-user.target.wants/ssh.service
elif [ -e /root/lib/systemd/system/ssh.service ]; then
    ln -sfn /lib/systemd/system/ssh.service /root/etc/systemd/system/multi-user.target.wants/ssh.service
fi
