[greeter]
background=/usr/share/ananas/login.png
theme-name=Yaru-dark
icon-theme-name=Yaru
font-name=DejaVu Sans 11
xft-antialias=true
xft-hintstyle=hintslight
indicators=~host;~spacer;~clock;~spacer;~session;~language;~power
user-background=false
clock-format=%H:%M
position=50%, 68%
default-user-image=/usr/share/ananas/icon-256.png
