[LightDM]
minimum-vt=1

[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=xfce
greeter-hide-users=false
allow-guest=false
greeter-show-manual-login=false
display-setup-script=/usr/local/bin/ananas-plymouth-quit
session-setup-script=/usr/local/bin/ananas-plymouth-quit
