export USERNAME="ananas"
export USERFULLNAME="Użytkownik live"
export HOST="ananas"
# Casper włącza swoje poprawki dla Ubuntu tylko przy tej nazwie.
export BUILD_SYSTEM="Ubuntu"
export FLAVOUR="AnanasOS"
