---
defaultFileSystemType: ext4
availableFileSystemTypes: ["ext4"]
efiSystemPartition: "/boot/efi"
efiSystemPartitionName: EFI
efiSystemPartitionSize: 512M
userSwapChoices:
  - none
  - small
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: none
defaultPartitionTableType: gpt
