---
defaultGroups:
  - adm
  - cdrom
  - sudo
  - dip
  - plugdev
  - lpadmin
doAutologin: false
setRootPassword: false
doReusePassword: false
availableShells: /bin/bash
sudoersGroup: sudo
passwordRequirements:
  minLength: 1
  maxLength: -1
userShell: /bin/bash
