Window.SetBackgroundTopColor (0.0, 0.0, 0.0);
Window.SetBackgroundBottomColor (0.0, 0.0, 0.0);

logo_image = Image ("logo.png");
logo_sprite = Sprite (logo_image);
logo_sprite.SetX (-4000);
logo_sprite.SetY (-4000);

fun place_sprites ()
{
    if (Window.GetWidth () < 64)
    {
        logo_sprite.SetX (-4000);
        logo_sprite.SetY (-4000);
        return;
    }
    logo_sprite.SetX (Window.GetWidth () / 2 - logo_image.GetWidth () / 2);
    logo_sprite.SetY (Window.GetHeight () / 2 - logo_image.GetHeight () / 2);
}

place_sprites ();
Window.SetRefreshFunction (place_sprites);
